# Generated by Django 3.0.8 on 2020-07-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200729_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
