# Generated by Django 3.0.8 on 2020-07-30 12:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200729_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=api.models.default_image, upload_to=api.models.upload_path),
        ),
    ]
